# Generated by Django 5.0.1 on 2024-03-02 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfoodapi', '0002_alter_client_photo_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 13, 52, 18, 142015, tzinfo=datetime.timezone.utc)),
        ),
    ]
